# Generated by Django 5.0.6 on 2026-08-15 05:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.member_profile_pic_path),
        ),
    ]
