# Generated by Django 5.0.6 on 2026-08-15 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('decoration', 'Decoration'), ('pandal', 'Pandal / Mandapam'), ('lighting', 'Lighting & Electrical'), ('sound', 'Sound System'), ('music', 'Music / DJ / Drums'), ('idol', 'Idol / Statue'), ('pooja', 'Pooja Materials'), ('priest', 'Priest / Purohit'), ('prasadam', 'Prasadam / Food'), ('flowers', 'Flowers & Garlands'), ('transport', 'Transport / Vehicle'), ('printing', 'Printing & Flex'), ('publicity', 'Publicity / Advertising'), ('water', 'Water / Drinking Water'), ('cleaning', 'Cleaning & Sanitation'), ('security', 'Security'), ('permissions', 'Permissions / Government Fees'), ('misc', 'Miscellaneous')], default='misc', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.committee')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
