# Generated by Django 5.0.6 on 2026-08-17 07:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.committee_icon_path),
        ),
    ]
